appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZFqPDnwqEnc62oS6PDvd7ha76baRK+H1tN7+M5uk0p2/8hCx666RimDFmUa94OgrSbG3SBISHY7gQF9LjYZwT3UtkFUG0mn+7yW8XxSEX2iouKCBmPP8g03iONgLyzn9sd7zCabykrYkmpo0NH4wTxhvP5mtqfqP8InhAEgQoCm0MBAmwrXZv5gFBnZNMci8cTc+dtBe47R3ce8At2fIrn5YWFy42iaiDdowIf2vB+Ujc74ZyNdia9Fw365usPifbqI2Ev3VT1pz9Xftle2JBwmCWy7KhMqOypkPJm61dDE0YLnG7dR4zkqHCKBGKNwGYfLfio9dSpw939hHPbJ9enWuRXoU/w2BSE07QvBWqrNJQPxP45C9Dn7JNh0fpo+zeRRJMuqK8oVsQ2I83ldS/EZb03kulTOxANy0mBjAbOsBcsvxM4tV9rfUh7rEKMugmdTpX8AWrpvuMk1D+hnkfzDvm+fWqapNDEoAtXjrUGDjby18wc1O3xE7qg8ajqcPVNSUBn35mIMSgzpw91QyNoPvOuBD0FgRTEwkyR4a/sAkK12jz8UI/LHbIi6nRiHWdhxpk4non3okgSIw0QNEUJHaqZt1A6j2zMBERMME6mqxAkBDRWk63qSSSLp9uoZ7Apn926i1ni1BDj3wwyjsNzbic25eJEG7XfxUSKgNvBo=}
bot:
  automerge: true
